---

controller:
  service:
    type: LoadBalancer
    # todo: specify ip address (scw lb ip create)
    loadBalancerIP: "1.2.3.4"
    annotations:
      service.beta.kubernetes.io/scw-loadbalancer-proxy-protocol-v2: "true"
      service.beta.kubernetes.io/scw-loadbalancer-use-hostname: "true"
  config:
    use-proxy-protocol: "true"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
