---

image:
  name: "gitops-backend"
  tag: "v0.0.3"

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: api-backend-gitops.foucron.fr
      paths:
        - path: /
          pathType: Prefix
