---

image:
  name: "gitops-backend"
  tag: "v0.0.4"

env:
  - name: RAILS_MASTER_KEY
    valueFrom:
      secretKeyRef:
        name: backend-secrets
        key: railsMasterKey

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: api-backend-gitops.foucron.fr
      paths:
        - path: /
          pathType: Prefix
